query GetRecipeList {
    getRecipeList {
        id
        image
        name
        description
        cookingTime
        instructions
        prepTime
        ingredients
        serves
        tips
    }
}

query GetCategoriesList($search: String, $page: Int) {
    getCategoryList(search: $search, page: $page) {
        id
        name
    }
}

mutation CreateOrUpdateRecipe($recipe: RecipeInput!, $recipeId: ID) {
    createOrUpdateRecipe(recipe: $recipe, recipeId: $recipeId) {
        id
        image
        name
        description
        cookingTime
        instructions
        prepTime
        ingredients
        serves
        tips
    }
}

mutation DeleteRecipe($recipeId: ID!) {
    deleteRecipe(recipeId: $recipeId)
}
