type Recipe {
    id: ID!
    category: Category!
    name: String!
    description: String!
    image: String!
    prepTime: Int!
    cookingTime: Int!
    serves: Int!
    ingredients: [String]!
    instructions: [String]!
    tips: [String]!
}

input RecipeInput {
    name: String!
    description: String!
    image: Upload!
    prepTime: Int!
    cookingTime: Int!
    serves: Int!
    ingredients: [String!]!
    instructions: [String!]!
    tips: [String!]!
    category: [ID!]!
}
