enum Role {
    admin
    user
}

type User {
    id: ID!
    email: String!
    name: String!
    firstName: String!
    role: Role
    phoneNumber: String
}

extend type Query {
    getUserList: [User!]!
    me: User
}
